/**
 * ============================================================================
 * EXPORT SCHEMA HEADERS
 * ============================================================================
 *
 * Mara's idea: Export all sheet headers to markdown for Claude Code visibility.
 * Run this manually, then copy output to SCHEMA_HEADERS.md in GitHub.
 *
 * Usage: Run exportAllHeaders() from Apps Script editor
 *
 * ============================================================================
 */

function exportAllHeaders() {
  var SIM_SSID = '1-0GNeCzqrDmmOy1wOScryzdRd82syq0Z_wZ7dTH8Bjk';
  var ss = SpreadsheetApp.openById(SIM_SSID);
  var sheets = ss.getSheets();

  var output = [];
  output.push('# GodWorld Schema Headers');
  output.push('');
  output.push('**Auto-generated by exportAllHeaders()**');
  output.push('');
  output.push('**Last Updated:** ' + new Date().toISOString().split('T')[0]);
  output.push('');
  output.push('---');
  output.push('');

  // Sort sheets alphabetically
  sheets.sort(function(a, b) {
    return a.getName().localeCompare(b.getName());
  });

  for (var i = 0; i < sheets.length; i++) {
    var sheet = sheets[i];
    var name = sheet.getName();

    // Skip hidden sheets or sheets starting with underscore
    if (sheet.isSheetHidden() || name.charAt(0) === '_') {
      continue;
    }

    var lastCol = sheet.getLastColumn();
    var rowCount = sheet.getLastRow();

    output.push('## ' + name);
    output.push('');
    output.push('- **Rows:** ' + rowCount);
    output.push('- **Columns:** ' + lastCol);
    output.push('');

    if (lastCol > 0) {
      var headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0];

      output.push('| Col | Header |');
      output.push('|-----|--------|');

      for (var c = 0; c < headers.length; c++) {
        var colLetter = columnToLetter_(c + 1);
        var header = headers[c] || '(empty)';
        output.push('| ' + colLetter + ' | ' + header + ' |');
      }
    } else {
      output.push('*(Empty sheet)*');
    }

    output.push('');
    output.push('---');
    output.push('');
  }

  var markdown = output.join('\n');

  // Log it (can copy from execution log)
  Logger.log(markdown);

  // Also show in a dialog for easy copying
  var html = HtmlService.createHtmlOutput(
    '<pre style="font-size:11px; max-height:500px; overflow:auto;">' +
    markdown.replace(/</g, '&lt;').replace(/>/g, '&gt;') +
    '</pre>' +
    '<p><button onclick="google.script.host.close()">Close</button></p>'
  ).setWidth(600).setHeight(500);

  SpreadsheetApp.getUi().showModalDialog(html, 'Schema Headers - Copy This');

  return markdown;
}

/**
 * Export headers for a single sheet (useful for quick checks)
 */
function exportSingleSheetHeaders(sheetName) {
  var SIM_SSID = '1-0GNeCzqrDmmOy1wOScryzdRd82syq0Z_wZ7dTH8Bjk';
  var ss = SpreadsheetApp.openById(SIM_SSID);
  var sheet = ss.getSheetByName(sheetName);

  if (!sheet) {
    Logger.log('Sheet not found: ' + sheetName);
    return null;
  }

  var lastCol = sheet.getLastColumn();
  if (lastCol === 0) {
    Logger.log(sheetName + ': (empty)');
    return [];
  }

  var headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0];

  Logger.log('=== ' + sheetName + ' ===');
  for (var c = 0; c < headers.length; c++) {
    Logger.log(columnToLetter_(c + 1) + ': ' + (headers[c] || '(empty)'));
  }

  return headers;
}

/**
 * Helper: Convert column number to letter (1=A, 27=AA, etc.)
 */
function columnToLetter_(col) {
  var letter = '';
  while (col > 0) {
    var mod = (col - 1) % 26;
    letter = String.fromCharCode(65 + mod) + letter;
    col = Math.floor((col - 1) / 26);
  }
  return letter;
}
