/**
 * ============================================================================
 * PRESS_DRAFTS WRITER v1.3
 * ============================================================================
 *
 * Records article drafts generated by the Media Room with calendar context.
 * Called when Media Room produces content based on engine signals.
 *
 * v1.4 Changes:
 * - Stopped writing dead calendar columns (I-N now empty strings)
 *   Calendar data is in ctx.summary — sheet duplication was never read
 * - Removed dead query functions: getDraftsByHoliday_, getDraftsBySportsSeason_
 *
 * v1.3 Enhancements:
 * - LinkedStoryline column: Row number in Storyline_Tracker (if any)
 * - StorylineType column: arc/question/thread/mystery/etc.
 *
 * v1.2 Enhancements:
 * - LinkedCitizen column: POPID of featured citizen (if any)
 * - CitizenArchetype, CitizenTone, CitizenNeighborhood columns
 *
 * SCHEMA (20 columns — I-N deprecated):
 * Timestamp | Cycle | Reporter | StoryType | SignalSource | SummaryPrompt |
 * DraftText | Status | (Season) | (Holiday) | (HolidayPriority) | (IsFirstFriday) |
 * (IsCreationDay) | (SportsSeason) | LinkedCitizen | CitizenArchetype | CitizenTone |
 * CitizenNeighborhood | LinkedStoryline | StorylineType
 *
 * STATUS VALUES:
 * - draft: Initial state, awaiting review
 * - published: Approved and "printed"
 * - killed: Rejected/spiked
 * - held: On hold for future use
 *
 * ============================================================================
 */


/**
 * Records a single press draft to the Press_Drafts ledger.
 *
 * @param {Object} ctx - Engine context (needs ctx.ss for spreadsheet access)
 * @param {string} reporter - Journalist name (e.g., "Elena Reyes")
 * @param {string} storyType - Type of story (breaking, feature, opinion, profile, etc.)
 * @param {string} signalSource - What triggered the story (shock-flag, health-crisis, pattern-wave, arc, etc.)
 * @param {string} summaryPrompt - The hook/angle/lede
 * @param {string} draftText - Full article text
 * @param {string} [status] - Optional status (defaults to "draft")
 * @param {Object} [citizenInfo] - v1.2: Optional citizen link info
 * @param {string} [citizenInfo.popId] - Citizen POPID
 * @param {string} [citizenInfo.archetype] - Citizen archetype
 * @param {string} [citizenInfo.tone] - Citizen tone
 * @param {string} [citizenInfo.neighborhood] - Citizen neighborhood
 * @param {Object} [storylineInfo] - v1.3: Optional storyline link info
 * @param {number} [storylineInfo.rowNumber] - Row number in Storyline_Tracker
 * @param {string} [storylineInfo.type] - Storyline type (arc/question/thread/etc.)
 * @returns {boolean} Success indicator
 */
function recordPressDraft_(ctx, reporter, storyType, signalSource, summaryPrompt, draftText, status, citizenInfo, storylineInfo) {

  var ss = ctx.ss;
  if (!ss) {
    Logger.log('recordPressDraft_: No spreadsheet in context');
    return false;
  }

  var HEADERS = [
    'Timestamp',         // A
    'Cycle',             // B
    'Reporter',          // C
    'StoryType',         // D
    'SignalSource',      // E
    'SummaryPrompt',     // F
    'DraftText',         // G
    'Status',            // H
    // Calendar columns (deprecated v1.4 — kept for sheet alignment)
    'Season',            // I
    'Holiday',           // J
    'HolidayPriority',   // K
    'IsFirstFriday',     // L
    'IsCreationDay',     // M
    'SportsSeason',      // N
    // v1.2: Citizen columns
    'LinkedCitizen',     // O
    'CitizenArchetype',  // P
    'CitizenTone',       // Q
    'CitizenNeighborhood',// R
    // v1.3: Storyline columns
    'LinkedStoryline',   // S
    'StorylineType'      // T
  ];

  // Ensure sheet exists
  var sheet = ss.getSheetByName('Press_Drafts');
  if (!sheet) {
    sheet = ss.insertSheet('Press_Drafts');
    sheet.appendRow(HEADERS);
    sheet.setFrozenRows(1);
    sheet.getRange(1, 1, 1, HEADERS.length).setFontWeight('bold');
    sheet.setColumnWidth(6, 300); // SummaryPrompt
    sheet.setColumnWidth(7, 500); // DraftText
  }

  var cycle = 0;
  if (ctx.config && ctx.config.cycleCount) {
    cycle = ctx.config.cycleCount;
  } else if (ctx.summary && ctx.summary.cycleId) {
    cycle = ctx.summary.cycleId;
  }

  var now = ctx.now || new Date();
  var finalStatus = status || 'draft';

  // v1.2: Extract citizen info
  var citizen = citizenInfo || {};
  var linkedCitizen = citizen.popId || '';
  var citizenArchetype = citizen.archetype || '';
  var citizenTone = citizen.tone || '';
  var citizenNeighborhood = citizen.neighborhood || '';

  // v1.3: Extract storyline info
  var storyline = storylineInfo || {};
  var linkedStoryline = storyline.rowNumber || '';
  var storylineType = storyline.type || '';

  var row = [
    now,                    // A  Timestamp
    cycle,                  // B  Cycle
    reporter || 'Unknown',  // C  Reporter
    storyType || 'general', // D  StoryType
    signalSource || '',     // E  SignalSource
    summaryPrompt || '',    // F  SummaryPrompt
    draftText || '',        // G  DraftText
    finalStatus,            // H  Status
    // Calendar columns deprecated v1.4 (empty strings preserve alignment)
    '',                     // I  (was Season)
    '',                     // J  (was Holiday)
    '',                     // K  (was HolidayPriority)
    '',                     // L  (was IsFirstFriday)
    '',                     // M  (was IsCreationDay)
    '',                     // N  (was SportsSeason)
    // v1.2: Citizen columns
    linkedCitizen,          // O  LinkedCitizen
    citizenArchetype,       // P  CitizenArchetype
    citizenTone,            // Q  CitizenTone
    citizenNeighborhood,    // R  CitizenNeighborhood
    // v1.3: Storyline columns
    linkedStoryline,        // S  LinkedStoryline
    storylineType           // T  StorylineType
  ];

  try {
    sheet.appendRow(row);
    var citizenNote = linkedCitizen ? ' | Citizen: ' + linkedCitizen + ' (' + citizenArchetype + ')' : '';
    var storylineNote = linkedStoryline ? ' | Storyline: ' + linkedStoryline : '';
    Logger.log('recordPressDraft_ v1.3: Logged draft by ' + reporter + ' (' + storyType + ')' + citizenNote + storylineNote);
    return true;
  } catch (e) {
    Logger.log('recordPressDraft_ error: ' + e.message);
    return false;
  }
}


/**
 * Records multiple press drafts at once (batch version).
 *
 * @param {Object} ctx - Engine context
 * @param {Array} drafts - Array of draft objects
 * @returns {number} Count of drafts recorded
 *
 * Each draft object should have:
 * {
 *   reporter: string,
 *   storyType: string,
 *   signalSource: string,
 *   summaryPrompt: string,
 *   draftText: string,
 *   status: string (optional),
 *   citizenInfo: { popId, archetype, tone, neighborhood } (optional, v1.2),
 *   storylineInfo: { rowNumber, type } (optional, v1.3)
 * }
 */
function recordPressDraftsBatch_(ctx, drafts) {

  var ss = ctx.ss;
  if (!ss) {
    Logger.log('recordPressDraftsBatch_: No spreadsheet in context');
    return 0;
  }

  if (!drafts || drafts.length === 0) {
    Logger.log('recordPressDraftsBatch_: No drafts to record');
    return 0;
  }

  var HEADERS = [
    'Timestamp',         // A
    'Cycle',             // B
    'Reporter',          // C
    'StoryType',         // D
    'SignalSource',      // E
    'SummaryPrompt',     // F
    'DraftText',         // G
    'Status',            // H
    // Calendar columns (deprecated v1.4 — kept for sheet alignment)
    'Season',            // I
    'Holiday',           // J
    'HolidayPriority',   // K
    'IsFirstFriday',     // L
    'IsCreationDay',     // M
    'SportsSeason',      // N
    // v1.2: Citizen columns
    'LinkedCitizen',     // O
    'CitizenArchetype',  // P
    'CitizenTone',       // Q
    'CitizenNeighborhood',// R
    // v1.3: Storyline columns
    'LinkedStoryline',   // S
    'StorylineType'      // T
  ];

  // Ensure sheet exists
  var sheet = ss.getSheetByName('Press_Drafts');
  if (!sheet) {
    sheet = ss.insertSheet('Press_Drafts');
    sheet.appendRow(HEADERS);
    sheet.setFrozenRows(1);
    sheet.getRange(1, 1, 1, HEADERS.length).setFontWeight('bold');
    sheet.setColumnWidth(6, 300);
    sheet.setColumnWidth(7, 500);
  }

  var cycle = 0;
  if (ctx.config && ctx.config.cycleCount) {
    cycle = ctx.config.cycleCount;
  } else if (ctx.summary && ctx.summary.cycleId) {
    cycle = ctx.summary.cycleId;
  }

  var now = ctx.now || new Date();

  var rows = [];
  var citizenCount = 0;
  var storylineCount = 0;
  for (var i = 0; i < drafts.length; i++) {
    var d = drafts[i];
    // v1.2: Extract citizen info from draft object
    var cit = d.citizenInfo || {};
    var linkedCitizen = cit.popId || '';
    var citizenArchetype = cit.archetype || '';
    var citizenTone = cit.tone || '';
    var citizenNeighborhood = cit.neighborhood || '';
    if (linkedCitizen) citizenCount++;

    // v1.3: Extract storyline info from draft object
    var stl = d.storylineInfo || {};
    var linkedStoryline = stl.rowNumber || '';
    var storylineType = stl.type || '';
    if (linkedStoryline) storylineCount++;

    rows.push([
      now,                    // A  Timestamp
      cycle,                  // B  Cycle
      d.reporter || 'Unknown',// C  Reporter
      d.storyType || 'general', // D  StoryType
      d.signalSource || '',   // E  SignalSource
      d.summaryPrompt || '',  // F  SummaryPrompt
      d.draftText || '',      // G  DraftText
      d.status || 'draft',    // H  Status
      // Calendar columns deprecated v1.4 (empty strings preserve alignment)
      '',                     // I  (was Season)
      '',                     // J  (was Holiday)
      '',                     // K  (was HolidayPriority)
      '',                     // L  (was IsFirstFriday)
      '',                     // M  (was IsCreationDay)
      '',                     // N  (was SportsSeason)
      // v1.2: Citizen columns
      linkedCitizen,          // O  LinkedCitizen
      citizenArchetype,       // P  CitizenArchetype
      citizenTone,            // Q  CitizenTone
      citizenNeighborhood,    // R  CitizenNeighborhood
      // v1.3: Storyline columns
      linkedStoryline,        // S  LinkedStoryline
      storylineType           // T  StorylineType
    ]);
  }

  try {
    var startRow = sheet.getLastRow() + 1;
    sheet.getRange(startRow, 1, rows.length, HEADERS.length).setValues(rows);
    var citizenNote = citizenCount > 0 ? ' | Citizens: ' + citizenCount : '';
    var storylineNote = storylineCount > 0 ? ' | Storylines: ' + storylineCount : '';
    Logger.log('recordPressDraftsBatch_ v1.4: Logged ' + rows.length + ' drafts' + citizenNote + storylineNote);
    return rows.length;
  } catch (e) {
    Logger.log('recordPressDraftsBatch_ error: ' + e.message);
    return 0;
  }
}


/**
 * Updates the status of an existing draft.
 * 
 * @param {Object} ctx - Engine context
 * @param {number} rowNumber - Row number (1-indexed, header is row 1)
 * @param {string} newStatus - New status (draft, published, killed, held)
 * @returns {boolean} Success indicator
 */
function updateDraftStatus_(ctx, rowNumber, newStatus) {
  
  var ss = ctx.ss;
  var sheet = ss.getSheetByName('Press_Drafts');
  
  if (!sheet) {
    Logger.log('updateDraftStatus_: Press_Drafts sheet not found');
    return false;
  }

  var validStatuses = ['draft', 'published', 'killed', 'held'];
  if (validStatuses.indexOf(newStatus) === -1) {
    Logger.log('updateDraftStatus_: Invalid status "' + newStatus + '"');
    return false;
  }

  try {
    // Status is column 8
    sheet.getRange(rowNumber, 8).setValue(newStatus);
    Logger.log('updateDraftStatus_: Row ' + rowNumber + ' → ' + newStatus);
    return true;
  } catch (e) {
    Logger.log('updateDraftStatus_ error: ' + e.message);
    return false;
  }
}


/**
 * Gets all drafts with a specific status.
 * 
 * @param {Object} ctx - Engine context
 * @param {string} status - Status to filter by
 * @returns {Array} Array of draft objects
 */
function getDraftsByStatus_(ctx, status) {
  
  var ss = ctx.ss;
  var sheet = ss.getSheetByName('Press_Drafts');
  
  if (!sheet) {
    return [];
  }

  var data = sheet.getDataRange().getValues();
  var headers = data[0];
  var results = [];

  for (var i = 1; i < data.length; i++) {
    var row = data[i];
    // Status is column 8 (index 7)
    if (row[7] === status) {
      results.push({
        rowNumber: i + 1,
        timestamp: row[0],
        cycle: row[1],
        reporter: row[2],
        storyType: row[3],
        signalSource: row[4],
        summaryPrompt: row[5],
        draftText: row[6],
        status: row[7],
        // v1.1: Calendar context
        season: row[8] || '',
        holiday: row[9] || 'none',
        holidayPriority: row[10] || 'none',
        isFirstFriday: row[11] || false,
        isCreationDay: row[12] || false,
        sportsSeason: row[13] || 'off-season',
        // v1.2: Citizen context
        linkedCitizen: row[14] || '',
        citizenArchetype: row[15] || '',
        citizenTone: row[16] || '',
        citizenNeighborhood: row[17] || '',
        // v1.3: Storyline context
        linkedStoryline: row[18] || '',
        storylineType: row[19] || ''
      });
    }
  }

  return results;
}


/**
 * Gets drafts from a specific cycle.
 * 
 * @param {Object} ctx - Engine context
 * @param {number} cycle - Cycle number to filter by
 * @returns {Array} Array of draft objects
 */
function getDraftsByCycle_(ctx, cycle) {
  
  var ss = ctx.ss;
  var sheet = ss.getSheetByName('Press_Drafts');
  
  if (!sheet) {
    return [];
  }

  var data = sheet.getDataRange().getValues();
  var results = [];

  for (var i = 1; i < data.length; i++) {
    var row = data[i];
    // Cycle is column 2 (index 1)
    if (row[1] === cycle) {
      results.push({
        rowNumber: i + 1,
        timestamp: row[0],
        cycle: row[1],
        reporter: row[2],
        storyType: row[3],
        signalSource: row[4],
        summaryPrompt: row[5],
        draftText: row[6],
        status: row[7],
        // v1.1: Calendar context
        season: row[8] || '',
        holiday: row[9] || 'none',
        holidayPriority: row[10] || 'none',
        isFirstFriday: row[11] || false,
        isCreationDay: row[12] || false,
        sportsSeason: row[13] || 'off-season',
        // v1.2: Citizen context
        linkedCitizen: row[14] || '',
        citizenArchetype: row[15] || '',
        citizenTone: row[16] || '',
        citizenNeighborhood: row[17] || '',
        // v1.3: Storyline context
        linkedStoryline: row[18] || '',
        storylineType: row[19] || ''
      });
    }
  }

  return results;
}


/**
 * v1.2: Gets drafts featuring a specific citizen.
 *
 * @param {Object} ctx - Engine context
 * @param {string} popId - Citizen POPID to filter by
 * @returns {Array} Array of draft objects
 */
function getDraftsByCitizen_(ctx, popId) {

  var ss = ctx.ss;
  var sheet = ss.getSheetByName('Press_Drafts');

  if (!sheet) {
    return [];
  }

  var data = sheet.getDataRange().getValues();
  var results = [];

  for (var i = 1; i < data.length; i++) {
    var row = data[i];
    // LinkedCitizen is column 15 (index 14)
    if (row[14] === popId) {
      results.push({
        rowNumber: i + 1,
        timestamp: row[0],
        cycle: row[1],
        reporter: row[2],
        storyType: row[3],
        signalSource: row[4],
        summaryPrompt: row[5],
        draftText: row[6],
        status: row[7],
        season: row[8] || '',
        holiday: row[9] || 'none',
        holidayPriority: row[10] || 'none',
        isFirstFriday: row[11] || false,
        isCreationDay: row[12] || false,
        sportsSeason: row[13] || 'off-season',
        linkedCitizen: row[14] || '',
        citizenArchetype: row[15] || '',
        citizenTone: row[16] || '',
        citizenNeighborhood: row[17] || '',
        // v1.3: Storyline context
        linkedStoryline: row[18] || '',
        storylineType: row[19] || ''
      });
    }
  }

  return results;
}


/**
 * v1.2: Gets drafts by citizen archetype.
 *
 * @param {Object} ctx - Engine context
 * @param {string} archetype - Archetype to filter by (Connector, Striver, etc.)
 * @returns {Array} Array of draft objects
 */
function getDraftsByArchetype_(ctx, archetype) {

  var ss = ctx.ss;
  var sheet = ss.getSheetByName('Press_Drafts');

  if (!sheet) {
    return [];
  }

  var data = sheet.getDataRange().getValues();
  var results = [];

  for (var i = 1; i < data.length; i++) {
    var row = data[i];
    // CitizenArchetype is column 16 (index 15)
    if (row[15] === archetype) {
      results.push({
        rowNumber: i + 1,
        timestamp: row[0],
        cycle: row[1],
        reporter: row[2],
        storyType: row[3],
        signalSource: row[4],
        summaryPrompt: row[5],
        draftText: row[6],
        status: row[7],
        season: row[8] || '',
        holiday: row[9] || 'none',
        holidayPriority: row[10] || 'none',
        isFirstFriday: row[11] || false,
        isCreationDay: row[12] || false,
        sportsSeason: row[13] || 'off-season',
        linkedCitizen: row[14] || '',
        citizenArchetype: row[15] || '',
        citizenTone: row[16] || '',
        citizenNeighborhood: row[17] || '',
        // v1.3: Storyline context
        linkedStoryline: row[18] || '',
        storylineType: row[19] || ''
      });
    }
  }

  return results;
}


/**
 * v1.2: Gets citizen coverage statistics.
 * Returns which citizens have been featured and how often.
 *
 * @param {Object} ctx - Engine context
 * @returns {Object} Map of popId → { count, lastCycle, archetypes, neighborhoods }
 */
function getCitizenCoverageStats_(ctx) {

  var ss = ctx.ss;
  var sheet = ss.getSheetByName('Press_Drafts');

  if (!sheet) {
    return {};
  }

  var data = sheet.getDataRange().getValues();
  var stats = {};

  for (var i = 1; i < data.length; i++) {
    var row = data[i];
    var popId = row[14];
    if (!popId) continue;

    if (!stats[popId]) {
      stats[popId] = {
        count: 0,
        lastCycle: 0,
        archetype: row[15] || '',
        neighborhood: row[17] || '',
        storyTypes: {}
      };
    }

    stats[popId].count++;
    var cycle = row[1] || 0;
    if (cycle > stats[popId].lastCycle) {
      stats[popId].lastCycle = cycle;
    }

    var storyType = row[3] || 'general';
    stats[popId].storyTypes[storyType] = (stats[popId].storyTypes[storyType] || 0) + 1;
  }

  return stats;
}


/**
 * v1.3: Gets drafts linked to a specific storyline.
 *
 * @param {Object} ctx - Engine context
 * @param {number} storylineRow - Row number in Storyline_Tracker to filter by
 * @returns {Array} Array of draft objects
 */
function getDraftsByStoryline_(ctx, storylineRow) {

  var ss = ctx.ss;
  var sheet = ss.getSheetByName('Press_Drafts');

  if (!sheet) {
    return [];
  }

  var data = sheet.getDataRange().getValues();
  var results = [];

  for (var i = 1; i < data.length; i++) {
    var row = data[i];
    // LinkedStoryline is column 19 (index 18)
    if (row[18] === storylineRow || row[18] === String(storylineRow)) {
      results.push({
        rowNumber: i + 1,
        timestamp: row[0],
        cycle: row[1],
        reporter: row[2],
        storyType: row[3],
        signalSource: row[4],
        summaryPrompt: row[5],
        draftText: row[6],
        status: row[7],
        season: row[8] || '',
        holiday: row[9] || 'none',
        holidayPriority: row[10] || 'none',
        isFirstFriday: row[11] || false,
        isCreationDay: row[12] || false,
        sportsSeason: row[13] || 'off-season',
        linkedCitizen: row[14] || '',
        citizenArchetype: row[15] || '',
        citizenTone: row[16] || '',
        citizenNeighborhood: row[17] || '',
        linkedStoryline: row[18] || '',
        storylineType: row[19] || ''
      });
    }
  }

  return results;
}


/**
 * v1.3: Gets storyline coverage statistics.
 * Returns which storylines have been covered and how often.
 *
 * @param {Object} ctx - Engine context
 * @returns {Object} Map of storylineRow → { count, lastCycle, types, statuses }
 */
function getStorylineCoverage_(ctx) {

  var ss = ctx.ss;
  var sheet = ss.getSheetByName('Press_Drafts');

  if (!sheet) {
    return {};
  }

  var data = sheet.getDataRange().getValues();
  var stats = {};

  for (var i = 1; i < data.length; i++) {
    var row = data[i];
    var storylineRow = row[18];
    if (!storylineRow) continue;

    var key = String(storylineRow);
    if (!stats[key]) {
      stats[key] = {
        count: 0,
        lastCycle: 0,
        storylineType: row[19] || '',
        storyTypes: {},
        statuses: {}
      };
    }

    stats[key].count++;
    var cycle = row[1] || 0;
    if (cycle > stats[key].lastCycle) {
      stats[key].lastCycle = cycle;
    }

    var storyType = row[3] || 'general';
    stats[key].storyTypes[storyType] = (stats[key].storyTypes[storyType] || 0) + 1;

    var status = row[7] || 'draft';
    stats[key].statuses[status] = (stats[key].statuses[status] || 0) + 1;
  }

  return stats;
}


/**
 * v1.3: Gets drafts by storyline type.
 *
 * @param {Object} ctx - Engine context
 * @param {string} storylineType - Type to filter (arc/question/thread/mystery/etc.)
 * @returns {Array} Array of draft objects
 */
function getDraftsByStorylineType_(ctx, storylineType) {

  var ss = ctx.ss;
  var sheet = ss.getSheetByName('Press_Drafts');

  if (!sheet) {
    return [];
  }

  var data = sheet.getDataRange().getValues();
  var results = [];

  for (var i = 1; i < data.length; i++) {
    var row = data[i];
    // StorylineType is column 20 (index 19)
    if (row[19] === storylineType) {
      results.push({
        rowNumber: i + 1,
        timestamp: row[0],
        cycle: row[1],
        reporter: row[2],
        storyType: row[3],
        signalSource: row[4],
        summaryPrompt: row[5],
        draftText: row[6],
        status: row[7],
        season: row[8] || '',
        holiday: row[9] || 'none',
        holidayPriority: row[10] || 'none',
        isFirstFriday: row[11] || false,
        isCreationDay: row[12] || false,
        sportsSeason: row[13] || 'off-season',
        linkedCitizen: row[14] || '',
        citizenArchetype: row[15] || '',
        citizenTone: row[16] || '',
        citizenNeighborhood: row[17] || '',
        linkedStoryline: row[18] || '',
        storylineType: row[19] || ''
      });
    }
  }

  return results;
}


/**
 * v1.1: Upgrades existing Press_Drafts sheet to add calendar columns.
 * Run once to upgrade v1.0 sheets to v1.1 format.
 * 
 * @param {Object} ctx - Engine context
 */
function upgradePressDraftsSheet_(ctx) {
  var ss = ctx.ss;
  var sheet = ss.getSheetByName('Press_Drafts');
  if (!sheet) return;

  var headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];

  // Check if calendar columns exist
  var hasSeason = headers.indexOf('Season') >= 0;

  if (!hasSeason) {
    // Add calendar columns
    var lastCol = sheet.getLastColumn();
    var newHeaders = ['Season', 'Holiday', 'HolidayPriority', 'IsFirstFriday', 'IsCreationDay', 'SportsSeason'];

    sheet.getRange(1, lastCol + 1, 1, newHeaders.length).setValues([newHeaders]);
    sheet.getRange(1, lastCol + 1, 1, newHeaders.length).setFontWeight('bold');

    // Set defaults for existing rows
    var lastRow = sheet.getLastRow();
    if (lastRow > 1) {
      var defaults = [];
      for (var i = 2; i <= lastRow; i++) {
        defaults.push(['', 'none', 'none', false, false, 'off-season']);
      }
      sheet.getRange(2, lastCol + 1, lastRow - 1, 6).setValues(defaults);
    }

    Logger.log('upgradePressDraftsSheet_ v1.1: Added 6 calendar columns to Press_Drafts');
  }

  // v1.2: Check for citizen columns
  var headersNow = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  var hasLinkedCitizen = headersNow.indexOf('LinkedCitizen') >= 0;

  if (!hasLinkedCitizen) {
    var lastColNow = sheet.getLastColumn();
    var citizenHeaders = ['LinkedCitizen', 'CitizenArchetype', 'CitizenTone', 'CitizenNeighborhood'];

    sheet.getRange(1, lastColNow + 1, 1, citizenHeaders.length).setValues([citizenHeaders]);
    sheet.getRange(1, lastColNow + 1, 1, citizenHeaders.length).setFontWeight('bold');

    // Set empty defaults for existing rows
    var lastRowNow = sheet.getLastRow();
    if (lastRowNow > 1) {
      var citizenDefaults = [];
      for (var j = 2; j <= lastRowNow; j++) {
        citizenDefaults.push(['', '', '', '']);
      }
      sheet.getRange(2, lastColNow + 1, lastRowNow - 1, 4).setValues(citizenDefaults);
    }

    Logger.log('upgradePressDraftsSheet_ v1.2: Added 4 citizen columns to Press_Drafts');
  }

  // v1.3: Check for storyline columns
  var headersV13 = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  var hasLinkedStoryline = headersV13.indexOf('LinkedStoryline') >= 0;

  if (!hasLinkedStoryline) {
    var lastColV13 = sheet.getLastColumn();
    var storylineHeaders = ['LinkedStoryline', 'StorylineType'];

    sheet.getRange(1, lastColV13 + 1, 1, storylineHeaders.length).setValues([storylineHeaders]);
    sheet.getRange(1, lastColV13 + 1, 1, storylineHeaders.length).setFontWeight('bold');

    // Set empty defaults for existing rows
    var lastRowV13 = sheet.getLastRow();
    if (lastRowV13 > 1) {
      var storylineDefaults = [];
      for (var k = 2; k <= lastRowV13; k++) {
        storylineDefaults.push(['', '']);
      }
      sheet.getRange(2, lastColV13 + 1, lastRowV13 - 1, 2).setValues(storylineDefaults);
    }

    Logger.log('upgradePressDraftsSheet_ v1.3: Added 2 storyline columns to Press_Drafts');
  }
}


/**
 * ============================================================================
 * STORY TYPE CONSTANTS
 * ============================================================================
 * 
 * Use these when calling recordPressDraft_ for consistency:
 * 
 * STORY_TYPES = {
 *   BREAKING: 'breaking',      // Urgent news, shock events
 *   FEATURE: 'feature',        // In-depth coverage
 *   PROFILE: 'profile',        // Person-focused
 *   OPINION: 'opinion',        // Editorial/commentary
 *   ANALYSIS: 'analysis',      // Pattern/trend examination
 *   RECAP: 'recap',            // Event summary
 *   PREVIEW: 'preview',        // Upcoming event coverage
 *   HUMAN_INTEREST: 'human-interest',  // Soft news
 *   INVESTIGATIVE: 'investigative',    // Deep-dive
 *   SPORTS: 'sports',          // Athletics coverage
 *   CULTURE: 'culture',        // Arts/entertainment
 *   CIVIC: 'civic',            // Government/community
 *   HOLIDAY: 'holiday',        // v1.1: Holiday coverage
 *   FESTIVAL: 'festival'       // v1.1: Festival coverage
 * }
 * 
 * ============================================================================
 */


/**
 * ============================================================================
 * SIGNAL SOURCE CONSTANTS
 * ============================================================================
 * 
 * Use these to indicate what triggered the story:
 * 
 * SIGNAL_SOURCES = {
 *   SHOCK_FLAG: 'shock-flag',
 *   PATTERN_WAVE: 'pattern-wave',
 *   HEALTH_CRISIS: 'health-crisis',
 *   CRISIS_ARC: 'crisis-arc',
 *   STORY_SEED: 'story-seed',
 *   STORY_HOOK: 'story-hook',
 *   WORLD_EVENT: 'world-event',
 *   CITIZEN_EVENT: 'citizen-event',
 *   CULTURAL_ENTITY: 'cultural-entity',
 *   SPORTS_SEASON: 'sports-season',
 *   WEATHER: 'weather',
 *   ECONOMIC: 'economic',
 *   DEMOGRAPHIC: 'demographic',
 *   EDITORIAL: 'editorial',      // No signal, editor's choice
 *   HOLIDAY: 'holiday',          // v1.1: Holiday-triggered
 *   FIRST_FRIDAY: 'first-friday', // v1.1: First Friday triggered
 *   CREATION_DAY: 'creation-day'  // v1.1: Creation Day triggered
 * }
 * 
 * ============================================================================
 */


/**
 * ============================================================================
 * PRESS_DRAFTS REFERENCE v1.4
 * ============================================================================
 *
 * COLUMNS (20 — I-N deprecated):
 * A   Timestamp
 * B   Cycle
 * C   Reporter
 * D   StoryType
 * E   SignalSource
 * F   SummaryPrompt
 * G   DraftText
 * H   Status
 * I   (deprecated v1.4, was Season)
 * J   (deprecated v1.4, was Holiday)
 * K   (deprecated v1.4, was HolidayPriority)
 * L   (deprecated v1.4, was IsFirstFriday)
 * M   (deprecated v1.4, was IsCreationDay)
 * N   (deprecated v1.4, was SportsSeason)
 * O   LinkedCitizen (v1.2) - POPID of featured citizen
 * P   CitizenArchetype (v1.2) - Connector/Striver/Anchor/etc.
 * Q   CitizenTone (v1.2) - plain/noir/bright/tense/tender
 * R   CitizenNeighborhood (v1.2) - Citizen's neighborhood
 * S   LinkedStoryline (v1.3) - Row number in Storyline_Tracker
 * T   StorylineType (v1.3) - arc/question/thread/mystery/etc.
 *
 * Note: Calendar columns I-N were never read by any consumer.
 * Removed in v1.4. Existing rows retain historical data.
 *
 * QUERY FUNCTIONS (v1.2):
 * - getDraftsByCitizen_(ctx, 'POP-1234') - Find all stories featuring citizen
 * - getDraftsByArchetype_(ctx, 'Striver') - Find stories by citizen archetype
 * - getCitizenCoverageStats_(ctx) - Get coverage frequency stats per citizen
 *
 * NEW QUERY FUNCTIONS (v1.3):
 * - getDraftsByStoryline_(ctx, 5) - Find all stories linked to storyline row 5
 * - getDraftsByStorylineType_(ctx, 'arc') - Find stories by storyline type
 * - getStorylineCoverage_(ctx) - Get coverage stats per storyline
 *
 * CITIZEN INFO OBJECT (v1.2):
 * When calling recordPressDraft_ or batch, pass citizenInfo:
 * {
 *   popId: 'POP-1234',           // Citizen POPID
 *   archetype: 'Connector',      // From TraitProfile
 *   tone: 'bright',              // Derived from traits + QoL
 *   neighborhood: 'Temescal'     // Citizen's neighborhood
 * }
 *
 * STORYLINE INFO OBJECT (v1.3):
 * When calling recordPressDraft_ or batch, pass storylineInfo:
 * {
 *   rowNumber: 5,                // Row number in Storyline_Tracker
 *   type: 'arc'                  // Storyline type (arc/question/thread/etc.)
 * }
 *
 * STORYLINE TYPES:
 * - arc: Long-running narrative arc
 * - question: Open question needing answers
 * - thread: Ongoing topic thread
 * - mystery: Unresolved mystery
 * - developing: Breaking/developing story
 * - seasonal: Tied to season/time of year
 * - festival: Festival-related storyline
 * - sports: Sports-related storyline
 *
 * ============================================================================
 */