#!/usr/bin/env node
/**
 * chaosCarsMagnitudeReport.js — engine.11 T6.2 magnitude tuning report.
 *
 * [research-build] chaos-cars plan docs/plans/2026-05-07-chaos-cars-engine.md §T6.2.
 * Spec asks: "read 3+ live cycles' chaos_cars rows; per metric, distribution of
 * magnitudes, post-decay residual at cycle+1/+2/+3; confirm asymmetry holds."
 *
 * SCOPED, not built to spec verbatim — checked before writing (measure-twice):
 *   - NEIGHBORHOOD scope IS measurable. Neighborhood_Map is rebuilt every cycle with
 *     no cell history (§S265), but buildWorldSummary.js's City State section snapshots
 *     the 4 movable columns (Sentiment/RetailVitality/EventAttractiveness/CrimeIndex)
 *     per neighborhood every cycle it runs — output/world_summary_c{XX}.md IS the
 *     history the plan assumed didn't exist. This script parses those tables.
 *   - BUSINESS scope is NOT measurable this way. buildWorldSummary.js emits no
 *     per-cycle Business_Ledger table, and Business_Ledger itself is live single-state
 *     (no version history). Reported as an explicit gap, not silently skipped.
 *   - CITIZEN scope has no decay row by design (§S265 — the col-O fold is one-time).
 *
 * Confound, stated plainly: a neighborhood cell can move between cycles from the
 * chaos residual, the baseline neighborhoodPulse fold, AND any other same-cycle chaos
 * event touching the same cell — this is observational signal on real live data, not a
 * controlled single-cause measurement. Treat directional agreement as supporting
 * evidence for the asymmetry design, not proof of the exact decay rate.
 *
 * Run: node scripts/chaosCarsMagnitudeReport.js
 */
'use strict';

require('/root/GodWorld/lib/env');
const fs = require('fs');
const path = require('path');
const sheets = require('/root/GodWorld/lib/sheets');

const ROOT = path.resolve(__dirname, '..');
const NB_COLUMNS = ['Sentiment', 'RetailVitality', 'EventAttractiveness', 'CrimeIndex'];

function parseNeighborhoodTable(mdText) {
  const lines = mdText.split('\n');
  const headerIdx = lines.findIndex((l) => /^\|\s*Neighborhood\s*\|/.test(l));
  if (headerIdx === -1) return null;
  const table = {};
  for (let i = headerIdx + 2; i < lines.length; i++) {
    const line = lines[i];
    if (!line.startsWith('|')) break;
    const cells = line.split('|').map((c) => c.trim()).filter((_, idx, arr) => !(idx === 0 || idx === arr.length - 1));
    if (cells.length < 5) break;
    const [hood, sentiment, retail, event, crime] = cells;
    table[hood] = {
      Sentiment: parseFloat(sentiment.replace('+', '')),
      RetailVitality: parseFloat(retail),
      EventAttractiveness: parseFloat(event),
      CrimeIndex: parseFloat(crime)
    };
  }
  return table;
}

function loadWorldSummaryNeighborhoodTables() {
  const files = fs.readdirSync(path.join(ROOT, 'output')).filter((f) => /^world_summary_c\d+\.md$/.test(f));
  const byCycle = {};
  for (const f of files) {
    const cycle = Number(f.match(/c(\d+)\.md$/)[1]);
    const text = fs.readFileSync(path.join(ROOT, 'output', f), 'utf8');
    const table = parseNeighborhoodTable(text);
    if (table) byCycle[cycle] = table;
  }
  return byCycle;
}

async function main() {
  const chaosRows = await sheets.getSheetAsObjects('Chaos_Cars').catch(() => []);
  const nbTables = loadWorldSummaryNeighborhoodTables();
  const availableCycles = Object.keys(nbTables).map(Number).sort((a, b) => a - b);

  const nbEvents = chaosRows.filter((r) => r.TargetScope === 'neighborhood' && NB_COLUMNS.includes(r.PrimaryMetric));
  const bizEvents = chaosRows.filter((r) => r.TargetScope === 'business');

  const measured = [];
  const unmeasurable = [];
  for (const ev of nbEvents) {
    const c0 = Number(ev.CycleId);
    const c1 = c0 + 1;
    if (!(nbTables[c0] && nbTables[c1] && nbTables[c0][ev.TargetId] && nbTables[c1][ev.TargetId])) {
      unmeasurable.push(ev);
      continue;
    }
    const before = nbTables[c0][ev.TargetId][ev.PrimaryMetric];
    const after = nbTables[c1][ev.TargetId][ev.PrimaryMetric];
    const magnitude = Number(ev.MetricMagnitude);
    measured.push({
      cycle: c0, neighborhood: ev.TargetId, metric: ev.PrimaryMetric,
      direction: magnitude >= 0 ? 'up' : 'down', magnitude, before, after,
      observedDelta: Number((after - before).toFixed(4))
    });
  }

  const lines = [];
  lines.push('# Chaos Cars Magnitude Report (T6.2)');
  lines.push('');
  lines.push('engine.11 — `docs/plans/2026-05-07-chaos-cars-engine.md`. Generated by `scripts/chaosCarsMagnitudeReport.js`.');
  lines.push('');
  lines.push(`**Live \`Chaos_Cars\` rows read:** ${chaosRows.length}. **\`world_summary\` cycles available for neighborhood history:** ${availableCycles.join(', ') || 'none'}.`);
  lines.push('');
  lines.push('## Scope note (checked before writing, not assumed)');
  lines.push('');
  lines.push('- **Neighborhood** — measurable. `world_summary`\'s City State neighborhood table snapshots the 4 movable columns every cycle it runs; this IS the cross-cycle history the plan assumed did not exist.');
  lines.push('- **Business** — NOT measurable this way. `buildWorldSummary.js` emits no per-cycle Business_Ledger table, and `Business_Ledger` is live single-state with no version history. Not built; reported as a gap below, not silently skipped.');
  lines.push('- **Citizen** — no decay row by design (§S265 Design Finalization — the col-O fold is one-time, not a recurring decay).');
  lines.push('- **Confound:** a neighborhood cell moves from the chaos residual, the baseline `neighborhoodPulse` fold, AND any other same-cycle chaos event on the same cell. This is observational signal on real live data, not a controlled single-cause measurement — directional agreement supports the asymmetry design, it does not prove an exact decay rate (that stays Q2, open in the plan, tunable at Phase 6).');
  lines.push('');
  lines.push('## Neighborhood events — measured (cycle N → N+1 observed)');
  lines.push('');
  if (measured.length) {
    lines.push('| Cycle | Neighborhood | Metric | Direction | Magnitude | Before | After | Observed Δ |');
    lines.push('|---|---|---|---|---|---|---|---|');
    for (const m of measured) {
      lines.push(`| ${m.cycle} | ${m.neighborhood} | ${m.metric} | ${m.direction} | ${m.magnitude} | ${m.before} | ${m.after} | ${m.observedDelta} |`);
    }
  } else {
    lines.push('_(no neighborhood chaos event has both cycle N and N+1 world_summary snapshots available)_');
  }
  lines.push('');

  const upEvents = measured.filter((m) => m.direction === 'up');
  const downEvents = measured.filter((m) => m.direction === 'down');
  const upReverted = upEvents.filter((m) => m.observedDelta <= 0).length; // moved back down toward baseline or held
  const downPersisted = downEvents.filter((m) => m.observedDelta <= 0).length; // stayed down or fell further

  lines.push('## Asymmetry signal (directional only — see confound note)');
  lines.push('');
  lines.push(`- Up-direction events measured: ${upEvents.length}; moved back toward/below prior value by next cycle: ${upReverted}.`);
  lines.push(`- Down-direction events measured: ${downEvents.length}; stayed down or fell further by next cycle: ${downPersisted}.`);
  lines.push(measured.length
    ? '_(Small sample from live data — this is a directional check, not a decay-rate calibration. Q2 in the plan stays open; DECAY_RULES values are starters per T4.1.)_'
    : '_(insufficient overlapping cycle data to compute — need more consecutive world_summary files)_');
  lines.push('');

  lines.push(`## Business events — NOT measured (gap, ${bizEvents.length} live rows)`);
  lines.push('');
  lines.push('No historical `Business_Ledger` snapshot exists and `buildWorldSummary.js` does not emit a business table. Measuring `applyChaosDecay_`\'s effect on `Annual_Revenue`/`Employee_Count` requires either (a) a new per-cycle Business_Ledger dump (like `scripts/dumpLedger.js` for Simulation_Ledger), or (b) reading the live sheet at successive real cycle boundaries going forward. Neither exists yet — filing as an open gap, not building blind.');
  lines.push('');

  if (unmeasurable.length) {
    lines.push(`## Neighborhood events skipped — no overlapping world_summary data (${unmeasurable.length})`);
    lines.push('');
    lines.push('Cycles: ' + [...new Set(unmeasurable.map((e) => e.CycleId))].sort().join(', '));
    lines.push('');
  }

  const reportPath = path.join(ROOT, 'output', 'chaos_cars_magnitude_report.md');
  fs.writeFileSync(reportPath, lines.join('\n'));
  console.log('Wrote', reportPath, `(${measured.length} measured, ${unmeasurable.length} skipped, ${bizEvents.length} business rows unmeasurable)`);
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { parseNeighborhoodTable, loadWorldSummaryNeighborhoodTables };
}

if (require.main === module) {
  main().catch((err) => {
    console.error('chaosCarsMagnitudeReport FAILED:', err.message);
    process.exit(1);
  });
}
