#!/usr/bin/env node

const assert = require('assert');
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const {
  parseArgs,
  cycleFromName,
  artifactStem,
  reportsFromPulse,
  flaggedFromPulse,
  safeToQuoteArticle,
  stableHash,
  mergeManifest,
  isCompletedManifest,
  buildSourcePack,
  buildBoundedNewsSource,
  parseJsonOutput,
  queryAnswer,
  renderResearchBrief,
  findSourceId,
  parseAddedSourceId,
  parseCreatedArtifactId,
  sourceTitle,
  dailyPrompt,
  dailyAudioFocus,
  SOURCE_VERSION,
  DEFAULT_AUDIO_LENGTH,
  DAILY_NEWS_IDENTITY,
} = require('./notebooklmDailyNews');
const notebookConfig = require('../config/notebooklm.json');

const syntheticInput = {
  cycle: 999,
  worldSummaryPath: 'output/world_summary_c999.md',
  worldSummary: [
    '# SYNTHETIC NON-CANON WORLD',
    '',
    'A visibly synthetic signal.',
    '',
    '_Generated by `scripts/buildWorldSummary.js` v0.0.0 from synthetic inputs._',
  ].join('\n'),
  reports: [{
    classification: 'UNGATED_SAMPLE',
    relativePath: 'output/cron-compare/samples/synthetic_c999.sample.md',
    body: '# Synthetic headline\n\nA visibly synthetic, non-canon report.',
  }],
  flagged: [{
    classification: 'FLAGGED_EXCLUSION',
    cycle: 999,
    relativePath: 'output/cron-compare/flagged/synthetic_c999.flags.json',
    reasonCount: 1,
  }],
};

{
  const args = parseArgs([
    'node', 'script',
    '--cycle=999', '--hours', '12', '--dry-run', '--no-audio', '--no-deliver',
  ]);
  assert.deepStrictEqual(args, {
    cycle: 999,
    hours: 12,
    audio: false,
    deliver: false,
    dryRun: true,
    routingShadow: false,
  });
}

{
  const args = parseArgs(['node', 'script', '--dry-run', '--routing-shadow']);
  assert.strictEqual(args.dryRun, true);
  assert.strictEqual(args.routingShadow, true);
  assert.throws(
    () => parseArgs(['node', 'script', '--routing-shadow']),
    /local-only and requires --dry-run/
  );
}

{
  const args = parseArgs(['node', 'script', '--resume-latest-audio']);
  assert.strictEqual(args.resumeLatestAudio, true);
  assert.strictEqual(args.audio, true);
  assert.strictEqual(args.deliver, true);
}

{
  const args = parseArgs(['node', 'script', '--force']);
  assert.strictEqual(args.force, true);
}

assert.strictEqual(cycleFromName('civic_c999_writer.sample.md'), 999);
assert.strictEqual(cycleFromName('no-cycle.md'), null);
assert.strictEqual(artifactStem('civic_c999_writer.sample.md'), 'civic_c999_writer');
assert.strictEqual(artifactStem('civic_c999_writer.flags.json'), 'civic_c999_writer');
assert.strictEqual(safeToQuoteArticle('A clean synthetic scene. What remains unknown?'), true);
assert.strictEqual(safeToQuoteArticle('The Tribune should ask the next question.'), false);
assert.strictEqual(safeToQuoteArticle('Here is the corrected article. What remains unknown?'), false);
assert.strictEqual(safeToQuoteArticle('{"packetContract":"LEP/2"}'), false);
assert.strictEqual(safeToQuoteArticle('A synthetic rider boarded BART. What remains unknown?'), true);
assert.strictEqual(safeToQuoteArticle('A hearing at Frank Ogawa Plaza. What remains unknown?'), false);
assert.strictEqual(stableHash({ b: 2 }), stableHash({ b: 2 }));
assert.deepStrictEqual(
  mergeManifest({ sourceIds: ['kept'], generatedAt: 'old' }, { generatedAt: 'new' }),
  { sourceIds: ['kept'], generatedAt: 'new' }
);
assert.strictEqual(isCompletedManifest({
  sourceVersion: SOURCE_VERSION,
  sourceIds: ['source'],
  audioPath: 'output/synthetic-noncanon.m4a',
  driveLink: 'https://example.invalid/synthetic',
}), true);
assert.strictEqual(isCompletedManifest({
  sourceVersion: '1.3',
  sourceIds: ['source'],
  audioPath: 'output/synthetic-noncanon.m4a',
  driveLink: 'https://example.invalid/synthetic',
}), false);
assert.strictEqual(isCompletedManifest({
  sourceVersion: '1.2',
  sourceIds: ['source'],
  audioPath: 'output/synthetic-noncanon.m4a',
  driveLink: 'https://example.invalid/synthetic',
}), false);
assert.strictEqual(isCompletedManifest({
  sourceVersion: SOURCE_VERSION,
  sourceIds: ['source'],
}), false);

{
  const first = buildSourcePack(syntheticInput);
  const second = buildSourcePack(syntheticInput);
  assert.strictEqual(first.hash, second.hash, 'same inputs must produce an idempotent pack hash');
  assert(first.text.includes('Authority order: current world summary first'));
  assert(first.text.includes('UNGATED_SAMPLE'));
  assert(first.text.includes('must not be presented as verified or published fact'));
  assert(first.text.includes('1 gate finding(s)'));
  assert(!first.text.includes('generatedAt'), 'wall-clock metadata must not perturb the source pack');
}

{
  const source = buildBoundedNewsSource({
    cycle: syntheticInput.cycle,
    worldSummary: syntheticInput.worldSummary,
    reports: syntheticInput.reports,
    archiveAnswer: 'Synthetic published background.',
  });
  assert(source.startsWith('# The Bay Tribune Daily News — Cycle 999'));
  assert(source.includes('Developing report — early newsroom sample.'));
  assert(source.includes('Synthetic published background.'));
  assert(!source.includes('Generated by `scripts/buildWorldSummary.js`'));
  assert(!source.includes('GodWorld Oakland, 2042'));
  assert(!source.includes('Artifact class:'));
  assert(!source.includes('Canon status:'));
  assert(!source.includes('Pack SHA-256:'));
  assert(!source.includes('FLAGGED_EXCLUSION'));
}

const syntheticPulse = {
  cycle: 999,
  fingerprint: 'synthetic-pulse-fingerprint',
  priorCompletedCycle: 998,
  counts: { angles: 1, w2Ready: 1, quotes: 1, passed: 1, rheaFlagged: 1, neverGated: 1, pending: 0 },
  assignments: [{
    key: 'civic_c999_synthetic_packet-v2',
    desk: 'civic',
    reporter: { name: 'Synthetic Reporter', popid: 'POP-99999' },
    headline: 'SYNTHETIC NON-CANON ASSIGNMENT',
    chase: 'Follow the supplied synthetic fact to its named test source.',
    quotes: [{
      name: 'Synthetic Citizen',
      popid: 'POP-99998',
      quote: 'I saw the synthetic test signal.',
      factIds: ['F-SYNTHETIC'],
      basis: 'direct-reaction',
    }],
    disposition: 'passed',
    flagPath: null,
  }, {
    key: 'business_c999_rhea_packet-v2',
    desk: 'business',
    reporter: null,
    headline: 'SYNTHETIC RHEA REJECTION',
    chase: null,
    quotes: [],
    disposition: 'rhea-flagged',
    flagPath: 'output/cron-compare/flagged/synthetic-rhea.flags.json',
    rheaFlagCount: 2,
  }, {
    key: 'sports_c999_shape_packet-v2',
    desk: 'sports',
    reporter: null,
    headline: 'SYNTHETIC NEVER GATED',
    chase: null,
    quotes: [],
    disposition: 'never-gated',
    flagPath: 'output/cron-compare/flagged/synthetic-shape.flags.json',
    rheaFlagCount: 0,
  }],
  dispositions: [{
    disposition: 'passed',
    wakePath: 'output/cron-compare/synthetic-pass.wake.json',
    flagPath: null,
    rheaFlagCount: 0,
    flagFindingCount: 0,
  }, {
    disposition: 'rhea-flagged',
    wakePath: 'output/cron-compare/synthetic-rhea.wake.json',
    flagPath: 'output/cron-compare/flagged/synthetic-rhea.flags.json',
    rheaFlagCount: 2,
    flagFindingCount: 1,
  }, {
    disposition: 'never-gated',
    wakePath: 'output/cron-compare/synthetic-shape.wake.json',
    flagPath: 'output/cron-compare/flagged/synthetic-shape.flags.json',
    rheaFlagCount: 0,
    flagFindingCount: 1,
  }],
  filings: { current: [], previous: [] },
  materialSignals: ['WORLD_HIGH_SIGNAL'],
};
const syntheticRouting = {
  profile: 'REPORTED_DAY',
  format: 'deep_dive',
  length: 'default',
  activationEligible: false,
  reasonCodes: ['RHEA_PASSED_1', 'REPORTED_THRESHOLD_UNSET_OBSERVE_ONLY'],
  sourceClasses: ['WORLD_STATE', 'W1_CHASE', 'W2_QUOTES', 'W3_PASSED'],
  dispositionCounts: { passed: 1, rheaFlagged: 1, neverGated: 1 },
};

{
  const shadowInput = Object.assign({}, syntheticInput, {
    pulse: syntheticPulse,
    routing: syntheticRouting,
    flagged: flaggedFromPulse(syntheticPulse),
  });
  const pack = buildSourcePack(shadowInput);
  assert(pack.text.includes('proposed profile: REPORTED_DAY'));
  assert(pack.text.includes('passed=1, rhea-flagged=1, never-gated=1'));
  assert(pack.text.includes('Follow the supplied synthetic fact'));
  assert(pack.text.includes('W2 Packet-backed quote coverage'));
  assert(pack.text.includes('disposition=rhea-flagged'));
  assert.notStrictEqual(
    pack.hash,
    buildSourcePack(Object.assign({}, shadowInput, {
      routing: Object.assign({}, syntheticRouting, { profile: 'CYCLE_OPEN' }),
    })).hash,
    'route changes must perturb the bounded-pack hash'
  );
}

{
  const source = buildBoundedNewsSource({
    cycle: syntheticInput.cycle,
    worldSummary: syntheticInput.worldSummary,
    pulse: syntheticPulse,
    reports: [{
      classification: 'PREVIOUS_FILING',
      relativePath: 'output/cron-compare/staged/synthetic_c998.staged.md',
      body: '# Synthetic prior filing\n\nA labeled prior-Cycle filing.',
    }],
    archiveAnswer: 'Synthetic published background.',
  });
  assert(source.includes('## What Tribune reporters are pursuing'));
  assert(source.includes('Follow the supplied synthetic fact'));
  assert(source.includes('## Interviews gathered by the Tribune'));
  assert(source.includes('Synthetic Citizen: “I saw the synthetic test signal.”'));
  assert(source.includes('Previous Cycle filing — continuity only'));
  assert(!source.includes('synthetic-rhea.flags.json'));
  assert(!source.includes('SYNTHETIC RHEA REJECTION'));
  assert(!source.includes('assignment JSON'));
}

{
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'nlm-daily-news-'));
  try {
    const relative = 'output/cron-compare/staged/synthetic_c999.staged.md';
    const file = path.join(root, relative);
    const body = '# SYNTHETIC VERIFIED\n\nExact hash required.';
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, body);
    const pulse = {
      filings: {
        current: [{
          cycle: 999,
          articlePath: relative,
          draftSha256: crypto.createHash('sha256').update(body).digest('hex'),
        }],
        previous: [],
      },
    };
    assert.strictEqual(reportsFromPulse(pulse, root).length, 1);
    pulse.filings.current[0].draftSha256 = 'stale-hash';
    assert.strictEqual(reportsFromPulse(pulse, root).length, 0);
    const unsafeBody = 'The Tribune should ask the next synthetic question.';
    fs.writeFileSync(file, unsafeBody);
    pulse.filings.current[0].draftSha256 = crypto.createHash('sha256').update(unsafeBody).digest('hex');
    assert.strictEqual(reportsFromPulse(pulse, root).length, 0,
      'an exact Rhea-sidecar hash must not bypass the current safe-to-quote gate');
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
}

const syntheticDigest = {
  path: 'output/citizen-day-digest.md',
  text: '# SYNTHETIC NON-CANON DIGEST\n\nA visibly synthetic citizen slice.',
};

{
  const withDigest = Object.assign({}, syntheticInput, { citizenDigest: syntheticDigest });
  const pack = buildSourcePack(withDigest);
  assert(pack.text.includes('## The people, in their own words — daily citizen digest'));
  assert(pack.text.includes('A visibly synthetic citizen slice.'));
  assert(pack.text.includes('a listening slice, not published reporting'));
  assert.notStrictEqual(
    pack.hash,
    buildSourcePack(syntheticInput).hash,
    'digest text must perturb the pack hash so reflections-only changes bust the no-op cache'
  );
}

{
  const source = buildBoundedNewsSource({
    cycle: syntheticInput.cycle,
    worldSummary: syntheticInput.worldSummary,
    citizenDigest: syntheticDigest,
    reports: syntheticInput.reports,
    archiveAnswer: 'Synthetic published background.',
  });
  assert(source.includes('## The people, in their own words'));
  assert(source.includes('A visibly synthetic citizen slice.'));
  assert(
    source.indexOf('## The people, in their own words') < source.indexOf('## Bay Tribune newsroom reports'),
    'digest section must precede the newsroom reports section'
  );
}

{
  const parsed = parseJsonOutput('{"answer":"Grounded answer","sources_used":[{"id":"s1"}]}', 'test');
  assert.strictEqual(queryAnswer(parsed), 'Grounded answer');
  assert.throws(() => parseJsonOutput('not-json', 'test'), /invalid JSON/);
}

{
  const sources = [
    { id: 'one', title: 'First' },
    { source_id: 'two', name: 'Second' },
  ];
  assert.strictEqual(findSourceId(sources, 'Second'), 'two');
  assert.strictEqual(findSourceId(sources, 'Missing'), null);
  assert.strictEqual(parseAddedSourceId('Done\nSource ID: abc-123\n'), 'abc-123');
  assert.throws(() => parseAddedSourceId('Done'), /without a Source ID/);
  assert.strictEqual(parseCreatedArtifactId('Audio started\nArtifact ID: art-123\n'), 'art-123');
  assert.throws(() => parseCreatedArtifactId('Audio started'), /without an Artifact ID/);
}

{
  const title = sourceTitle('current source pack', 999, 'abcdef1234567890');
  assert.strictEqual(title, 'The Bay Tribune Daily C999 — current source pack — abcdef123456');
  const prompt = dailyPrompt(999);
  assert.strictEqual(SOURCE_VERSION, '1.6');
  assert.strictEqual(DEFAULT_AUDIO_LENGTH, 'default');
  assert.strictEqual(notebookConfig.dailyNews.audioLength, 'default');
  assert(prompt.includes('The Bay Tribune daily news for Oakland for Cycle 999'));
  assert(!prompt.includes('GodWorld Oakland, 2042'));
  assert.strictEqual(dailyAudioFocus(), DAILY_NEWS_IDENTITY);
  assert.strictEqual(dailyAudioFocus(false), 'The Bay Tribune daily news for Oakland.');
  assert(dailyAudioFocus(true).startsWith(DAILY_NEWS_IDENTITY));
  assert(dailyAudioFocus(true).includes('00_AUDIO_DIRECTION_GUIDE'));
}

{
  const brief = renderResearchBrief(999, {
    answer: 'Synthetic continuity.',
    sources_used: [{ id: 's1', title: 'Synthetic source' }],
  }, {
    archiveNotebookId: 'synthetic-notebook',
    prompt: 'Synthetic prompt',
  });
  assert(brief.includes('Artifact class: NLM_RESEARCH_BRIEF'));
  assert(brief.includes('Canon status: NOT CANON'));
  assert(brief.includes('Synthetic continuity.'));
  assert(brief.includes('"id": "s1"'));
}

console.log('notebooklmDailyNews tests: PASS');
