#!/usr/bin/env node
/**
 * regenSchemaHeaders.js — Local Node mirror of utilities/exportAllHeaders().
 *
 * Reads every non-hidden, non-underscore-prefixed tab from the configured
 * spreadsheet and writes schemas/SCHEMA_HEADERS.md in the same format the
 * Apps Script generator produces. Use when clasp run is unavailable
 * (Apps Script not deployed as API executable) or when an engine-sheet
 * session needs to regen + commit in-place via the service account.
 *
 * Usage:
 *   node scripts/regenSchemaHeaders.js              # writes schemas/SCHEMA_HEADERS.md
 *   node scripts/regenSchemaHeaders.js --dry-run    # writes /tmp/SCHEMA_HEADERS.preview.md
 */

require('../lib/env');
const fs = require('fs');
const path = require('path');
const { google } = require('googleapis');

async function getClient() {
  const credentialsPath = process.env.GOOGLE_APPLICATION_CREDENTIALS
    || '/root/.config/godworld/credentials/service-account.json';
  const auth = new google.auth.GoogleAuth({
    keyFile: path.resolve(credentialsPath),
    scopes: ['https://www.googleapis.com/auth/spreadsheets']
  });
  return google.sheets({ version: 'v4', auth });
}

function getSpreadsheetId() {
  const id = process.env.GODWORLD_SHEET_ID;
  if (!id) throw new Error('GODWORLD_SHEET_ID not set');
  return id;
}

function columnToLetter(col) {
  let letter = '';
  while (col > 0) {
    const mod = (col - 1) % 26;
    letter = String.fromCharCode(65 + mod) + letter;
    col = Math.floor((col - 1) / 26);
  }
  return letter;
}

async function main() {
  const dryRun = process.argv.includes('--dry-run');
  const sheets = await getClient();
  const spreadsheetId = getSpreadsheetId();

  const meta = await sheets.spreadsheets.get({
    spreadsheetId,
    fields: 'sheets.properties(title,index,hidden)'
  });

  const tabs = meta.data.sheets
    .map(s => s.properties)
    .filter(p => !p.hidden && !p.title.startsWith('_'))
    .sort((a, b) => a.title.localeCompare(b.title));

  const today = new Date().toISOString().split('T')[0];

  const out = [];
  out.push('---');
  out.push('title: GodWorld Schema Headers');
  out.push('created: 2026-01-21');
  out.push('updated: ' + today);
  out.push('type: reference');
  out.push('tags: [schema, infrastructure, auto-generated, active]');
  out.push('sources:');
  out.push('  - Google Sheets live state (spreadsheet ID in config)');
  out.push('  - utilities/exportSchemaHeaders.js (generator)');
  out.push('pointers:');
  out.push('  - "[[SPREADSHEET]] — environment overview"');
  out.push('  - "[[SIMULATION_LEDGER]] — citizen-tab column map"');
  out.push('  - "[[index]] — catalog pointing here"');
  out.push('---');
  out.push('');
  out.push('# GodWorld Schema Headers');
  out.push('');
  out.push('**Auto-generated by exportAllHeaders()**');
  out.push('');
  out.push('**Last Updated:** ' + today);
  out.push('');
  out.push('---');
  out.push('');

  for (const tab of tabs) {
    const escaped = tab.title.replace(/'/g, "''");
    const resp = await sheets.spreadsheets.values.get({
      spreadsheetId,
      range: `'${escaped}'`
    });
    const values = resp.data.values || [];
    const lastRow = values.length;
    const lastCol = values.reduce((max, row) => Math.max(max, row.length), 0);
    const headers = values[0] || [];

    out.push('## ' + tab.title);
    out.push('');
    out.push('- **Rows:** ' + lastRow);
    out.push('- **Columns:** ' + lastCol);
    out.push('');

    if (lastCol > 0) {
      out.push('| Col | Header |');
      out.push('|-----|--------|');
      for (let c = 0; c < lastCol; c++) {
        const colLetter = columnToLetter(c + 1);
        const header = (headers[c] != null && headers[c] !== '') ? headers[c] : '(empty)';
        out.push('| ' + colLetter + ' | ' + header + ' |');
      }
    } else {
      out.push('*(Empty sheet)*');
    }

    out.push('');
    out.push('---');
    out.push('');
  }

  const markdown = out.join('\n');
  const target = dryRun
    ? '/tmp/SCHEMA_HEADERS.preview.md'
    : path.join(__dirname, '..', 'schemas', 'SCHEMA_HEADERS.md');

  fs.writeFileSync(target, markdown, 'utf8');
  console.log(`Wrote ${markdown.length} chars (${markdown.split('\n').length} lines, ${tabs.length} tabs) → ${target}`);
}

main().catch(err => { console.error(err); process.exit(1); });
