#!/usr/bin/env node
/**
 * rotateJournalRecent.js — S211
 *
 * Replaces the manual JOURNAL_RECENT.md rotation step in /session-end §2.5.
 * Reads the last 3 ## Session entries from JOURNAL.md and writes them to
 * JOURNAL_RECENT.md verbatim. Nightly reflections live inside JOURNAL.md as
 * ### sub-headings within session blocks (written by the discord-reflection
 * cron), so they propagate via readLast() automatically — no preservation
 * logic needed in this script.
 *
 * Same pattern as scripts/writeShippedBlock.js (S207): canonical source
 * (JOURNAL.md), mechanical derivation, no manual hand-rotation.
 */

const fs = require('fs');
const path = require('path');
const { readLast } = require('../lib/sessionLog');

const REPO_ROOT = path.resolve(__dirname, '..');
const JOURNAL_PATH = path.join(REPO_ROOT, 'docs/mags-corliss/JOURNAL.md');
const RECENT_PATH = path.join(REPO_ROOT, 'docs/mags-corliss/JOURNAL_RECENT.md');

const HEADER = `# Journal — Recent Entries

Last 3 entries from JOURNAL.md. Full archive at docs/mags-corliss/JOURNAL.md.

Auto-generated by \`scripts/rotateJournalRecent.js\` at session-end (S211). Do not edit by hand — edit JOURNAL.md and re-run the script.

---
`;

function main() {
  const entries = readLast(JOURNAL_PATH, 3);
  if (entries.length === 0) {
    console.error('No entries found in JOURNAL.md — aborting.');
    process.exit(1);
  }

  const entryBlocks = entries
    .map(e => `## ${e.step}\n${e.body.trimEnd()}\n\n---`)
    .join('\n\n');

  fs.writeFileSync(RECENT_PATH, HEADER + '\n' + entryBlocks + '\n');
  console.log(`Wrote JOURNAL_RECENT.md: ${entries.length} entries (${entries.map(e => e.step.split(' — ')[0]).join(', ')})`);
}

main();
