/**
 * validateEdition.contract.test.js — contract test for the programmatic
 * edition validation gate at scripts/validateEdition.js.
 *
 * Pairs with [[../docs/plans/2026-05-12-test-coverage-rollout]] §4.5. Two
 * sections:
 *
 *   Section A — structural source-level assertions (sub-second, no
 *   subprocess). Verifies the script's load-bearing primitives are present:
 *   severity constants, ENGINE_TERMS array with critical patterns, --no-sheets
 *   flag, exit-code documentation, all 11 check functions, async main entry.
 *
 *   Section B — fixture subprocess assertions (~10-15s, 8 parallel invocations
 *   on a 4-CPU box). E93 pinned as known-pass under current canon. E78/E85/E90
 *   pinned as historical snapshots with >= N CRITICAL floors — these editions
 *   were canon-clean at the time they shipped but the validator now sees them
 *   against the current truesource (council districts, mayor, officials all
 *   drifted across cycles). Floor assertions catch validator-going-silent
 *   regressions without being brittle to minor improvements. Four hand-crafted
 *   known-fail tmpfiles cover engine-language leak / real-name blocklist /
 *   vote-math mismatch / wrong-mayor — purely on edition text, no sheet data
 *   required (--no-sheets passed).
 *
 * Test design rationale + canon-drift discovery: S217 measure-twice surfaced
 * that the plan's "pin 78-93 as known-pass" assumption was wrong (only E93
 * passes under current canon). See plan §4.5 changelog.
 *
 * Run: node scripts/validateEdition.contract.test.js
 * Exits 0 on pass, 1 on failure.
 */

const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const { promisify } = require('util');
const execAsync = promisify(exec);

const ROOT = path.resolve(__dirname, '..');
const SCRIPT_PATH = path.resolve(__dirname, 'validateEdition.js');
const source = fs.readFileSync(SCRIPT_PATH, 'utf8');

// Canon files live under output/desk-packets/ which is gitignored. They exist
// locally (regenerated by buildDeskPackets.js) but not in CI. Section B's
// canon-dependent assertions (historical-snapshot floors + wrong-mayor)
// gracefully skip when canon is absent; structural Section A + engine-language
// + real-name + vote-math fixtures run in both environments.
const CANON_PRESENT =
  fs.existsSync(path.join(ROOT, 'output/desk-packets/base_context.json')) ||
  fs.existsSync(path.join(ROOT, 'output/desk-packets/truesource_reference.json'));

let passed = 0;
let failed = 0;
let skipped = 0;
function assert(label, cond, detail) {
  if (cond) { console.log(`  ok   ${label}`); passed++; }
  else { console.error(`  FAIL ${label}${detail ? ': ' + detail : ''}`); failed++; }
}
function skip(label, reason) {
  console.log(`  skip ${label} — ${reason}`);
  skipped++;
}

// ─── Section A — Structural contract (source-level) ──────────────────
console.log('═══ Section A — Structural contract (source-level)');

console.log('\nTest 1: source readable + non-trivial size');
{
  assert('script exists', fs.existsSync(SCRIPT_PATH));
  assert('source > 20KB (non-trivial)', source.length > 20000, `${source.length} bytes`);
}

console.log('\nTest 2: Severity constants present');
{
  assert("CRITICAL constant", /const\s+CRITICAL\s*=\s*['"]CRITICAL['"]/.test(source));
  assert("WARNING constant", /const\s+WARNING\s*=\s*['"]WARNING['"]/.test(source));
  assert("NOTE constant", /const\s+NOTE\s*=\s*['"]NOTE['"]/.test(source));
}

console.log('\nTest 3: ENGINE_TERMS contains load-bearing patterns');
{
  assert('ENGINE_TERMS array declared', /const\s+ENGINE_TERMS\s*=\s*\[/.test(source));
  // Each pattern is a literal regex inside the array — match the slash-delimited form.
  assert("'tension score' pattern", /\/\\btension\s+score\\b\//.test(source));
  assert("'severity level' pattern", /\/\\bseverity\s+level\\b\//.test(source));
  assert("'simulation' pattern", /\/\\bsimulation\\b\//.test(source));
  assert("'phase \\d+' pattern", /\/\\bphase\s+\\d\+\//.test(source));
  // S231 pipeline.28 G-W51: ledger removed from ENGINE_TERMS — overloaded
  // with journalism metaphor use ("on the ledger", "ledger entry"); was
  // BLOCKING-tier false-positive on natural prose. Real engine vocabulary
  // is unique (tension score / civic load / story seed / phase NN).
  assert("'ledger' pattern REMOVED (G-W51, was false-positive on metaphor)",
    !/\/\\bledger\\b\//.test(source));
  assert("'Edition \\d+' pattern", /\/\\bEdition\\s\+\\d\+\//.test(source));
}

console.log('\nTest 4: DEFENSIVE_TERMS array for DH-award conflicts');
{
  assert('DEFENSIVE_TERMS array declared', /const\s+DEFENSIVE_TERMS\s*=\s*\[/.test(source));
  assert("'gold glove' pattern present", /\/gold\s+glove\//i.test(source));
}

console.log('\nTest 5: --no-sheets flag parsed from argv');
{
  assert("NO_SHEETS = process.argv.includes('--no-sheets')",
    /NO_SHEETS\s*=\s*process\.argv\.includes\(['"]--no-sheets['"]\)/.test(source));
}

console.log('\nTest 6: Exit codes documented');
{
  // Doc comment block at top says: 0 = CLEAN, 1 = CRITICAL, 2 = File/data errors
  assert("'0 = CLEAN' documented", /0\s*=\s*CLEAN/.test(source));
  assert("'1 = CRITICAL' documented", /1\s*=\s*CRITICAL/.test(source));
  assert("'2 = File/data errors' documented", /2\s*=\s*File\/data\s*errors/.test(source));
  // process.exit calls — confirm both critical and clean paths still wire to argv
  assert('process.exit(0) for clean path', /process\.exit\(0\)/.test(source));
  assert('process.exit(1) for critical path', /process\.exit\(1\)/.test(source));
  assert('process.exit(2) for file-error path', /process\.exit\(2\)/.test(source));
}

console.log('\nTest 7: All 11 check functions present');
{
  const checkFns = [
    'checkCouncilNames', 'checkVoteMath', 'checkVoteBreakdownConsistency',
    'checkPlayerPositions', 'checkMayorName', 'checkRealNames',
    'checkEngineLanguage', 'checkPlayerFirstNames', 'checkCitizenNames',
    'checkInitiativeFacts', 'checkCivicOfficeNames'
  ];
  for (const fn of checkFns) {
    assert(`function ${fn}`, new RegExp(`function\\s+${fn}\\s*\\(`).test(source));
  }
}

console.log('\nTest 8: async main() entry');
{
  assert('async function main()', /async\s+function\s+main\s*\(\s*\)/.test(source));
}

// ─── Section B — Fixture subprocess (live execution) ──────────────────
console.log('\n═══ Section B — Fixture subprocess (live execution)');

const TMP_PREFIX = `/tmp/validateEdition_contract_${process.pid}`;
const TMP_ENGINE = `${TMP_PREFIX}_engine.txt`;
const TMP_REALNAME = `${TMP_PREFIX}_realname.txt`;
const TMP_VOTEMATH = `${TMP_PREFIX}_votemath.txt`;
const TMP_MAYOR = `${TMP_PREFIX}_mayor.txt`;

// Hand-crafted known-fail fixtures — minimal text that triggers a single
// check's CRITICAL path. Each fixture targets one check; validator runs all
// checks regardless, so other categories may also fire (harmless — assertions
// only require the targeted check's label to appear).
fs.writeFileSync(TMP_ENGINE,
  'The simulation entered its tension score window during phase 4.\n');
fs.writeFileSync(TMP_REALNAME,
  'Billy Donovan attended the council meeting last night.\n');
fs.writeFileSync(TMP_VOTEMATH,
  'The council passed 8-7 on the housing proposal after lengthy debate.\n');
fs.writeFileSync(TMP_MAYOR,
  'Mayor Smith addressed the press conference yesterday afternoon.\n');

async function runValidator(editionPath) {
  try {
    const { stdout, stderr } = await execAsync(
      `node "${SCRIPT_PATH}" "${editionPath}" --no-sheets`,
      { cwd: ROOT, maxBuffer: 10 * 1024 * 1024 }
    );
    return { status: 0, stdout, stderr };
  } catch (err) {
    return { status: err.code, stdout: err.stdout || '', stderr: err.stderr || '' };
  }
}

function countCriticals(stdout) {
  const m = stdout.match(/(\d+)\s+CRITICAL/);
  return m ? parseInt(m[1], 10) : 0;
}

(async () => {
  // 8 invocations in parallel — wall-clock should drop to slowest single run
  // + overhead (~7-10s on a 4-CPU box) vs ~55s serial.
  const [e93, e78, e85, e90, engineLeak, realName, voteMath, mayor] =
    await Promise.all([
      runValidator(path.join(ROOT, 'editions/cycle_pulse_edition_93.txt')),
      runValidator(path.join(ROOT, 'editions/cycle_pulse_edition_78.txt')),
      runValidator(path.join(ROOT, 'editions/cycle_pulse_edition_85.txt')),
      runValidator(path.join(ROOT, 'editions/cycle_pulse_edition_90.txt')),
      runValidator(TMP_ENGINE),
      runValidator(TMP_REALNAME),
      runValidator(TMP_VOTEMATH),
      runValidator(TMP_MAYOR),
    ]);

  // Cleanup tmpfiles
  for (const f of [TMP_ENGINE, TMP_REALNAME, TMP_VOTEMATH, TMP_MAYOR]) {
    try { fs.unlinkSync(f); } catch { /* ok */ }
  }

  console.log('\nTest 9: E93 known-pass under current canon');
  if (CANON_PRESENT) {
    assert('E93 exits 0', e93.status === 0, `exit=${e93.status}`);
    assert('E93 STATUS is PASSABLE or CLEAN',
      /STATUS:\s*(PASSABLE|CLEAN)/.test(e93.stdout));
  } else {
    skip('E93 exits 0', 'canon files absent (CI environment)');
    skip('E93 STATUS is PASSABLE or CLEAN', 'canon files absent (CI environment)');
  }

  // Historical snapshots — canon drifted across cycles (council districts,
  // officials reshuffled), so old editions now fail against current
  // truesource. Floor assertions catch validator-going-silent regressions
  // without locking specific issue counts that drift with each canon edit.
  console.log('\nTest 10: E78 historical snapshot — canon-drift floor');
  if (CANON_PRESENT) {
    assert('E78 exits 1', e78.status === 1, `exit=${e78.status}`);
    const n = countCriticals(e78.stdout);
    assert('E78 has >= 20 CRITICALs (snapshot floor)', n >= 20, `found ${n}`);
  } else {
    skip('E78 exits 1', 'canon files absent (CI environment)');
    skip('E78 >= 20 CRITICALs', 'canon files absent (CI environment)');
  }

  console.log('\nTest 11: E85 historical snapshot — canon-drift floor');
  if (CANON_PRESENT) {
    assert('E85 exits 1', e85.status === 1, `exit=${e85.status}`);
    const n = countCriticals(e85.stdout);
    assert('E85 has >= 5 CRITICALs (snapshot floor)', n >= 5, `found ${n}`);
  } else {
    skip('E85 exits 1', 'canon files absent (CI environment)');
    skip('E85 >= 5 CRITICALs', 'canon files absent (CI environment)');
  }

  console.log('\nTest 12: E90 historical snapshot — canon-drift floor');
  if (CANON_PRESENT) {
    assert('E90 exits 1', e90.status === 1, `exit=${e90.status}`);
    const n = countCriticals(e90.stdout);
    assert('E90 has >= 2 CRITICALs (snapshot floor)', n >= 2, `found ${n}`);
  } else {
    skip('E90 exits 1', 'canon files absent (CI environment)');
    skip('E90 >= 2 CRITICALs', 'canon files absent (CI environment)');
  }

  // Tests 13-15: each fixture deliberately triggers a violation that
  // validateEdition reports under a labeled section. The exit-code assertion
  // passes without canon (validateEdition returns non-zero on file-load
  // failures too), but the label-in-output assertion requires the check
  // function to actually run — which needs canon loaded. Guard the label
  // assertions with CANON_PRESENT.
  console.log('\nTest 13: Engine-language leak fixture triggers CRITICAL');
  {
    assert('engine-leak fixture exits 1', engineLeak.status === 1,
      `exit=${engineLeak.status}`);
    if (CANON_PRESENT) {
      assert('Engine Language label in output',
        /\[Engine Language\]/.test(engineLeak.stdout));
    } else {
      skip('Engine Language label in output', 'canon files absent (CI environment)');
    }
  }

  console.log('\nTest 14: Real-name blocklist fixture triggers CRITICAL');
  {
    assert('real-name fixture exits 1', realName.status === 1,
      `exit=${realName.status}`);
    if (CANON_PRESENT) {
      assert('Real-Name Screening label in output',
        /\[Real-Name Screening\]/.test(realName.stdout));
    } else {
      skip('Real-Name Screening label in output', 'canon files absent (CI environment)');
    }
  }

  console.log('\nTest 15: Vote-math mismatch fixture triggers CRITICAL');
  {
    assert('vote-math fixture exits 1', voteMath.status === 1,
      `exit=${voteMath.status}`);
    if (CANON_PRESENT) {
      assert('Vote Math label in output', /\[Vote Math\]/.test(voteMath.stdout));
    } else {
      skip('Vote Math label in output', 'canon files absent (CI environment)');
    }
  }

  console.log('\nTest 16: Wrong-mayor fixture triggers CRITICAL');
  if (CANON_PRESENT) {
    assert('wrong-mayor fixture exits 1', mayor.status === 1,
      `exit=${mayor.status}`);
    assert('Mayor Name label in output', /\[Mayor Name\]/.test(mayor.stdout));
  } else {
    skip('wrong-mayor fixture exits 1', 'canon files absent (CI environment)');
    skip('Mayor Name label in output', 'canon files absent (CI environment)');
  }

  console.log('\n' + '═'.repeat(60));
  const skipNote = skipped > 0 ? `, ${skipped} skipped` : '';
  console.log(`${passed} passed, ${failed} failed${skipNote}`);
  process.exit(failed === 0 ? 0 : 1);
})();
