#!/usr/bin/env node
/**
 * writeShippedBlock.js — Auto-generate "## Shipped Last Session" block in SESSION_CONTEXT.
 *
 * S207. The boot-handoff gap: SESSION_CONTEXT was bloating because it tried to narrate
 * what shipped each session. ROLLOUT is now canonical for closed work. This script gives
 * a fresh boot a compact, authoritative "what just shipped" surface — git log between
 * the last session boundary and HEAD, written verbatim into SESSION_CONTEXT.
 *
 * Flow at session-end (single invocation, no --finalize):
 *   1. Read .claude/state/shipped-block-boundary (= last work commit of previous session)
 *   2. git log boundary..HEAD --oneline --no-merges → filter Session-close subjects
 *   3. Splice block into SESSION_CONTEXT (replace existing or insert after first ---)
 *   4. Update boundary file to current HEAD
 *   5. Both SESSION_CONTEXT.md and the boundary state file get committed in
 *      the session-close commit
 *
 * Off-by-one handling: the boundary update writes HEAD (the last work commit BEFORE
 * the session-close commit). Next session, log will include the prior session-close
 * commit; the Session-close subject filter strips it.
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const BOUNDARY_FILE = path.join(ROOT, '.claude/state/shipped-block-boundary');
const SESSION_CONTEXT = path.join(ROOT, 'SESSION_CONTEXT.md');

function git(cmd) {
  return execSync(`git ${cmd}`, { cwd: ROOT }).toString().trim();
}

function getCurrentHead() {
  return git('rev-parse HEAD');
}

function readBoundary() {
  if (!fs.existsSync(BOUNDARY_FILE)) {
    try {
      return git('rev-parse HEAD~25');
    } catch {
      return git('rev-list --max-parents=0 HEAD');
    }
  }
  return fs.readFileSync(BOUNDARY_FILE, 'utf8').trim();
}

function writeBoundary(sha) {
  fs.mkdirSync(path.dirname(BOUNDARY_FILE), { recursive: true });
  fs.writeFileSync(BOUNDARY_FILE, sha + '\n');
}

function getCommitsSince(boundary) {
  let out;
  try {
    out = git(`log --oneline --no-merges ${boundary}..HEAD`);
  } catch (e) {
    return [];
  }
  if (!out) return [];
  return out
    .split('\n')
    .map(line => {
      const sp = line.indexOf(' ');
      return { sha: line.slice(0, sp), subject: line.slice(sp + 1) };
    })
    .filter(c => !/Session-close/i.test(c.subject));
}

function detectSessionTag() {
  const subj = git('log -1 --format=%s');
  const m = subj.match(/S(\d+)/);
  return m ? `S${m[1]}` : 'unknown';
}

function buildBlock(commits, sessionTag) {
  const header = `## Shipped Last Session (${sessionTag})`;
  const note = `*Auto-generated by \`scripts/writeShippedBlock.js\` at session-end. Source: \`git log\`. ROLLOUT_PLAN.md is canonical for what these commits accomplished.*`;
  if (commits.length === 0) {
    return `${header}\n\n${note}\n\n*(No qualifying commits since previous boundary.)*\n`;
  }
  const lines = commits.map(c => `- \`${c.sha}\` ${c.subject}`).join('\n');
  return `${header}\n\n${note}\n\n${lines}\n`;
}

function spliceBlock(content, block) {
  const marker = '## Shipped Last Session';
  const start = content.indexOf(marker);
  if (start !== -1) {
    const next = content.indexOf('\n---\n', start);
    if (next !== -1) {
      return content.slice(0, start) + block + '\n' + content.slice(next + 1);
    }
    return content.slice(0, start) + block;
  }
  const firstSep = content.indexOf('\n---\n');
  if (firstSep === -1) {
    return content + '\n\n---\n\n' + block + '\n---\n';
  }
  const insertAt = firstSep + '\n---\n'.length;
  return content.slice(0, insertAt) + '\n' + block + '\n---\n' + content.slice(insertAt);
}

function main() {
  if (!fs.existsSync(SESSION_CONTEXT)) {
    console.error(`SESSION_CONTEXT.md not found at ${SESSION_CONTEXT}`);
    process.exit(1);
  }

  const boundary = readBoundary();
  const head = getCurrentHead();
  const commits = getCommitsSince(boundary);
  const sessionTag = detectSessionTag();
  const block = buildBlock(commits, sessionTag);

  const content = fs.readFileSync(SESSION_CONTEXT, 'utf8');
  const updated = spliceBlock(content, block);
  fs.writeFileSync(SESSION_CONTEXT, updated);

  writeBoundary(head);

  console.log(`Wrote Shipped block: ${commits.length} commits (${sessionTag})`);
  console.log(`  boundary was: ${boundary.slice(0, 7)}`);
  console.log(`  boundary now: ${head.slice(0, 7)}`);
}

main();
