/**
 * ============================================================================
 * V3.2 STORY HOOK WRITER
 * ============================================================================
 *
 * Writes hooks to Story_Hook_Deck sheet with calendar context.
 *
 * v3.2 Enhancements:
 * - Calendar columns (Holiday, HolidayPriority, FirstFriday, CreationDay, SportsSeason)
 * - CalendarTrigger column for hooks generated by calendar events
 * - Aligned with GodWorld Calendar v1.0
 *
 * Previous features (v3.1):
 * - Hook type, domain, neighborhood
 * - Priority and linked arc tracking
 * - Suggested desks
 * 
 * ============================================================================
 */

function saveV3Hooks_(ctx) {
  const ss = ctx.ss;
  const hooks = ctx.summary.storyHooks || [];

  if (!hooks.length) return;

  // v3.2: Expanded headers with calendar columns
  const headers = [
    'Timestamp',        // A
    'Cycle',            // B
    'HookID',           // C
    'HookType',         // D
    'Domain',           // E
    'Neighborhood',     // F
    'Priority',         // G
    'HookText',         // H
    'LinkedArcID',      // I
    'SuggestedDesks',   // J
    'Holiday',          // K (v3.2)
    'HolidayPriority',  // L (v3.2)
    'FirstFriday',      // M (v3.2)
    'CreationDay',      // N (v3.2)
    'SportsSeason',     // O (v3.2)
    'CalendarTrigger'   // P (v3.2)
  ];

  const sheet = ensureSheet_(ss, 'Story_Hook_Deck', headers);

  const cycle = ctx.config.cycleCount || ctx.summary.cycleId;
  const now = ctx.now || new Date();

  // v3.2: Get current calendar context
  const holiday = ctx.summary.holiday || 'none';
  const holidayPriority = ctx.summary.holidayPriority || 'none';
  const isFirstFriday = ctx.summary.isFirstFriday || false;
  const isCreationDay = ctx.summary.isCreationDay || false;
  const sportsSeason = ctx.summary.sportsSeason || 'off-season';

  const rows = hooks.map(h => [
    now,
    cycle,
    h.hookId || '',
    h.hookType || 'signal',
    h.domain || '',
    h.neighborhood || '',
    h.priority || 1,
    h.text || '',
    h.linkedArcId || '',
    h.suggestedDesks || '',
    holiday,                              // v3.2
    holidayPriority,                      // v3.2
    isFirstFriday,                        // v3.2
    isCreationDay,                        // v3.2
    sportsSeason,                         // v3.2
    h.calendarTrigger || ''               // v3.2: If hook was calendar-triggered
  ]);

  const startRow = Math.max(sheet.getLastRow() + 1, 2);
  sheet.getRange(startRow, 1, rows.length, rows[0].length).setValues(rows);
}


/**
 * ============================================================================
 * STORY HOOK DECK SCHEMA v3.2
 * ============================================================================
 * 
 * COLUMNS (16):
 * A - Timestamp
 * B - Cycle
 * C - HookID
 * D - HookType (signal, arc-driven, pattern, calendar, etc.)
 * E - Domain
 * F - Neighborhood
 * G - Priority (1-5)
 * H - HookText
 * I - LinkedArcID
 * J - SuggestedDesks
 * K - Holiday (v3.2)
 * L - HolidayPriority (v3.2)
 * M - FirstFriday (v3.2)
 * N - CreationDay (v3.2)
 * O - SportsSeason (v3.2)
 * P - CalendarTrigger (v3.2) - Which calendar event triggered this hook
 * 
 * QUERY EXAMPLES:
 * - All Pride hooks: =FILTER(H:H, K:K="OaklandPride")
 * - First Friday hooks: =FILTER(H:H, M:M=TRUE)
 * - High priority playoff hooks: =FILTER(H:H, (G:G>=4)*(O:O="playoffs"))
 * - Calendar-triggered hooks: =FILTER(H:H, P:P<>"")
 * 
 * ============================================================================
 */