/**
 * ============================================================================
 * V3.3 STORY HOOK WRITER - Write-Intent Based
 * ============================================================================
 *
 * Writes hooks to Story_Hook_Deck sheet with calendar context.
 * Uses V3 write-intents model for persistence.
 *
 * v3.3 Changes:
 * - Uses queueBatchAppendIntent_ instead of direct writes
 * - Full dryRun/replay mode support
 * - ES5 compatible (removed const/let, arrow functions, .map())
 *
 * v3.2 Features (preserved):
 * - Calendar columns (Holiday, HolidayPriority, FirstFriday, CreationDay, SportsSeason)
 * - CalendarTrigger column for hooks generated by calendar events
 * - Aligned with GodWorld Calendar v1.0
 *
 * Previous features (v3.1):
 * - Hook type, domain, neighborhood
 * - Priority and linked arc tracking
 * - Suggested desks
 *
 * ============================================================================
 */

var HOOK_DECK_HEADERS = [
  'Timestamp',        // A
  'Cycle',            // B
  'HookID',           // C
  'HookType',         // D
  'Domain',           // E
  'Neighborhood',     // F
  'Priority',         // G
  'HookText',         // H
  'LinkedArcID',      // I
  'SuggestedDesks',   // J
  'Holiday',          // K (v3.2)
  'HolidayPriority',  // L (v3.2)
  'FirstFriday',      // M (v3.2)
  'CreationDay',      // N (v3.2)
  'SportsSeason',     // O (v3.2)
  'CalendarTrigger'   // P (v3.2)
];


function saveV3Hooks_(ctx) {
  var ss = ctx.ss;
  var hooks = ctx.summary.storyHooks || [];

  if (!hooks.length) return;

  // Initialize persist context if needed
  if (!ctx.persist) {
    initializePersistContext_(ctx);
  }

  // Ensure sheet exists with headers
  var sheet = ensureSheet_(ss, 'Story_Hook_Deck', HOOK_DECK_HEADERS);

  var S = ctx.summary;
  var cycle = ctx.config.cycleCount || S.cycleId;
  var now = ctx.now || new Date();

  // v3.2: Get current calendar context
  var holiday = S.holiday || 'none';
  var holidayPriority = S.holidayPriority || 'none';
  var isFirstFriday = S.isFirstFriday || false;
  var isCreationDay = S.isCreationDay || false;
  var sportsSeason = S.sportsSeason || 'off-season';

  // Build rows (ES5 compatible)
  var rows = [];
  for (var i = 0; i < hooks.length; i++) {
    var h = hooks[i];
    rows.push([
      now,                              // A  Timestamp
      cycle,                            // B  Cycle
      h.hookId || '',                   // C  HookID
      h.hookType || 'signal',           // D  HookType
      h.domain || '',                   // E  Domain
      h.neighborhood || '',             // F  Neighborhood
      h.priority || 1,                  // G  Priority
      h.text || '',                     // H  HookText
      h.linkedArcId || '',              // I  LinkedArcID
      h.suggestedDesks || '',           // J  SuggestedDesks
      holiday,                          // K  Holiday (v3.2)
      holidayPriority,                  // L  HolidayPriority (v3.2)
      isFirstFriday,                    // M  FirstFriday (v3.2)
      isCreationDay,                    // N  CreationDay (v3.2)
      sportsSeason,                     // O  SportsSeason (v3.2)
      h.calendarTrigger || ''           // P  CalendarTrigger (v3.2)
    ]);
  }

  // Queue batch append intent
  queueBatchAppendIntent_(
    ctx,
    'Story_Hook_Deck',
    rows,
    'Save ' + rows.length + ' story hooks for cycle ' + cycle,
    'media',
    100
  );

  Logger.log('saveV3Hooks_ v3.3: Queued ' + rows.length + ' hooks | Holiday: ' + holiday + ' | Sports: ' + sportsSeason);
}


/**
 * ============================================================================
 * STORY HOOK DECK SCHEMA v3.2
 * ============================================================================
 *
 * COLUMNS (16):
 * A - Timestamp
 * B - Cycle
 * C - HookID
 * D - HookType (signal, arc-driven, pattern, calendar, etc.)
 * E - Domain
 * F - Neighborhood
 * G - Priority (1-5)
 * H - HookText
 * I - LinkedArcID
 * J - SuggestedDesks
 * K - Holiday (v3.2)
 * L - HolidayPriority (v3.2)
 * M - FirstFriday (v3.2)
 * N - CreationDay (v3.2)
 * O - SportsSeason (v3.2)
 * P - CalendarTrigger (v3.2) - Which calendar event triggered this hook
 *
 * QUERY EXAMPLES:
 * - All Pride hooks: =FILTER(H:H, K:K="OaklandPride")
 * - First Friday hooks: =FILTER(H:H, M:M=TRUE)
 * - High priority playoff hooks: =FILTER(H:H, (G:G>=4)*(O:O="playoffs"))
 * - Calendar-triggered hooks: =FILTER(H:H, P:P<>"")
 *
 * ============================================================================
 */
